[tool.black]
line-length = 80
max-line-length = 80
target-version = ["py38", "py39"]
enforce_line_length = true
experimental_string_processing = true

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
